pragma circom 2.1.6;

// GENERATED by zk/scripts/gen-ncdf-circom.mjs — do not hand-edit. Regenerate and re-gate.
//
// THE STANDARD NORMAL CDF, COMPUTED IN A CIRCUIT.
//
// The roadmap said options-risk "requires exp and erf in-circuit, which is where this stops being
// arithmetic and starts being a research project", and greeksfp/greekssigned/parity were built to
// route around it by proving CONSISTENCY identities that cancel the transcendental instead of
// evaluating it. probe-cdf-residue.mjs measured the cost of that route: a service using
// Abramowitz-Stegun 7.1.26 instead of Hart satisfies ALL EIGHT identities to 3.3e-14 and prices a
// leg 19.4% wrong. So the identities are blind to the thing that matters, and put-call parity is
// blind too — the put is P = df*(K*N(-d2) - F*N(-d1)), so any N with N(-x) = 1 - N(x) makes
// C - P = df*(F - K) hold ALGEBRAICALLY with N cancelling.
//
// The premise was wrong, in the same way the Tier-3 premise was wrong. "erf" is not what the
// engine computes. The engine computes HART (1968):
//
//     N(-z) = e^{-z^2/2} * b(z) / d(z)        for 0 <= z < 7.0711
//
// A ratio is a multiplication: c*d = e*b. A polynomial is Horner. That leaves one transcendental,
// e^{-w} — and e^{-w} FACTORS over the binary expansion of w in a way erf does not:
//
//     w = sum_i b_i 2^i    =>    e^{-w} = prod_i (e^{-2^i})^{b_i}
//
// Every factor is a constant and every choice is a multiplexer, so exp is a product of selected
// constants — which is what a circuit does natively. The wall was never the transcendental. It was
// the fixed-point representation, exactly as it was for Tier 3.
//
// ── WHAT IS PROVEN ──
//   for the public point x, the public value n is the normal CDF at x, and the public value p is
//   its density, both evaluated by the recurrences below. The evaluator is pinned, not asserted:
//   every multiply carries a range-checked remainder, so the prover cannot choose a rounding.
//
// ── WHAT IS NOT ──
//   this pins n GIVEN x. It does not pin x. For options-risk, x is d1 or d2, and pinning those
//   needs ln(F/K) — which is the same exp gadget run backwards (L is the log of F/K iff
//   K*exp(L) = F), so it is another instance of this block and not a new problem. NOT BUILT HERE.
//   What IS measured in gateB7-5: n and p together over-determine x, so a caller who binds p to a
//   published gamma and n to a published delta pins x without any logarithm at all.
//
// ── THE TAIL ──
//   Hart switches to a continued fraction at z = 7.0711. This circuit does NOT carry that branch.
//   Above the split it proves a BOUND instead: the upper tail is under 2 / 2^40, and the
//   density under 8 / 2^40. That is a real weakening and it is published as `computed`, so a
//   reader can see which of the two statements they were given. Measured over a listed-book shape,
//   1.03% of legs land there; over a one-hour-to-one-week wing, 46.79% do.
//
// ── SCALE ── every quantity is an integer at 2^-40. The truncating multiply
//   out * 2^S + rem = a * b,  0 <= rem < 2^S
//   is one constraint plus an S-bit range check, and it is the dominant cost: 26 of them.

include "../../node_modules/circomlib/circuits/bitify.circom";
include "../../node_modules/circomlib/circuits/comparators.circom";
include "../../node_modules/circomlib/circuits/mux4.circom";

// a * b >> S, with the discarded remainder range-checked so the prover cannot pick a rounding.
// Without the range check `out` is unconstrained below the S-th bit and the whole evaluator is
// decoration — the same failure the mantissa lower bound in greeksfp existed to prevent.
template MulShift(S) {
    signal input a;
    signal input b;
    signal output out;
    signal rem;
    signal prod;
    prod <== a * b;
    out <-- prod \ (1 << S);
    rem <-- prod % (1 << S);
    prod === out * (1 << S) + rem;
    component rb = Num2Bits(S);
    rb.in <== rem;
}

template NormalCdf() {
    var S      = 40;
    var ONE    = 1099511627776;                 // 1.0
    var NB_X   = 52;
    var NB_R   = 101;                       // derived: max(cHat*dHat, eHat*bHat) + 2, not rounded up
    var NB_P   = 84;
    var TOLC   = 12;                        // ulp; derived, see the block at the c relation
    var TOLP   = 10;
    var ZSPLIT = 7774721279939;      // 7.07106781186547, where Hart changes branch
    var SQRT2PI = 2756066934468;     // computed by Machin + integer sqrt, not quoted from a table
    var CDF_TAIL = 2;                   // N(-7.0711), the tail bound
    var PHI_TAIL = 8;                  // phi(7.0711), the density bound

    // ---- public interface -----------------------------------------------------------------
    signal input xSign;      // 0 when x >= 0, 1 when x < 0
    signal input xMag;       // |x| * 2^S
    signal input nHat;       // the claimed N(x) * 2^S
    signal input pHat;       // the claimed density phi(x) * 2^S

    signal output computed;  // 1 when the CDF was evaluated, 0 when only the tail bound was proven
    signal output tailC;     // the bound in force above the split, published so it is not implied
    signal output tailP;
    tailC <== CDF_TAIL;
    tailP <== PHI_TAIL;

    xSign * (xSign - 1) === 0;
    component rx = Num2Bits(NB_X);   rx.in <== xMag;
    component rn = Num2Bits(S + 1);  rn.in <== nHat;      // N is in [0,1], so S+1 bits is exact
    component rp = Num2Bits(S);      rp.in <== pHat;      // phi <= 0.3990 < 1
    component nLe = LessEqThan(S + 2); nLe.in[0] <== nHat; nLe.in[1] <== ONE; nLe.out === 1;

    // ---- which branch -------------------------------------------------------------------
    component split = LessThan(NB_X + 1);
    split.in[0] <== xMag;
    split.in[1] <== ZSPLIT;
    computed <== split.out;

    // The evaluator ALWAYS runs, on a clamped argument, so its own range checks can never be the
    // thing that fails on a tail input. Only the binding of its output to nHat/pHat is conditional.
    // Running it on the raw xMag instead would make W overflow at |x| = 386, which a real book
    // reaches, and the circuit would refuse where it means to bound.
    signal zc;
    zc <== xMag + (1 - computed) * (ZSPLIT - 1 - xMag);

    // ---- W = z^2 / 2, at 2^-S ------------------------------------------------------------
    signal sq;
    sq <== zc * zc;
    signal W;
    signal wRem;
    W    <-- sq \ (1 << 41);
    wRem <-- sq % (1 << 41);
    sq === W * (1 << 41) + wRem;
    component wrb = Num2Bits(41);  wrb.in <== wRem;
    component wbits = Num2Bits(45);  wbits.in <== W;

    // ---- e^{-W}: 12 groups of 4 bits, one Mux4 and one MulShift each -------------------------
    // 192 constants, generated at 200 fractional bits and re-derived by the gate.
    component mx[12];
    component em[12];
    signal acc[13];
    acc[0] <== ONE;
    mx[0] = Mux4();
    mx[0].c[0] <== 1099511627776;
    mx[0].c[1] <== 1099511627775;
    mx[0].c[2] <== 1099511627774;
    mx[0].c[3] <== 1099511627773;
    mx[0].c[4] <== 1099511627772;
    mx[0].c[5] <== 1099511627771;
    mx[0].c[6] <== 1099511627770;
    mx[0].c[7] <== 1099511627769;
    mx[0].c[8] <== 1099511627768;
    mx[0].c[9] <== 1099511627767;
    mx[0].c[10] <== 1099511627766;
    mx[0].c[11] <== 1099511627765;
    mx[0].c[12] <== 1099511627764;
    mx[0].c[13] <== 1099511627763;
    mx[0].c[14] <== 1099511627762;
    mx[0].c[15] <== 1099511627761;
    mx[0].s[0] <== wbits.out[0];
    mx[0].s[1] <== wbits.out[1];
    mx[0].s[2] <== wbits.out[2];
    mx[0].s[3] <== wbits.out[3];
    em[0] = MulShift(S);   em[0].a <== acc[0];   em[0].b <== mx[0].out;   acc[1] <== em[0].out;
    mx[1] = Mux4();
    mx[1].c[0] <== 1099511627776;
    mx[1].c[1] <== 1099511627760;
    mx[1].c[2] <== 1099511627744;
    mx[1].c[3] <== 1099511627728;
    mx[1].c[4] <== 1099511627712;
    mx[1].c[5] <== 1099511627696;
    mx[1].c[6] <== 1099511627680;
    mx[1].c[7] <== 1099511627664;
    mx[1].c[8] <== 1099511627648;
    mx[1].c[9] <== 1099511627632;
    mx[1].c[10] <== 1099511627616;
    mx[1].c[11] <== 1099511627600;
    mx[1].c[12] <== 1099511627584;
    mx[1].c[13] <== 1099511627568;
    mx[1].c[14] <== 1099511627552;
    mx[1].c[15] <== 1099511627536;
    mx[1].s[0] <== wbits.out[4];
    mx[1].s[1] <== wbits.out[5];
    mx[1].s[2] <== wbits.out[6];
    mx[1].s[3] <== wbits.out[7];
    em[1] = MulShift(S);   em[1].a <== acc[1];   em[1].b <== mx[1].out;   acc[2] <== em[1].out;
    mx[2] = Mux4();
    mx[2].c[0] <== 1099511627776;
    mx[2].c[1] <== 1099511627520;
    mx[2].c[2] <== 1099511627264;
    mx[2].c[3] <== 1099511627008;
    mx[2].c[4] <== 1099511626752;
    mx[2].c[5] <== 1099511626496;
    mx[2].c[6] <== 1099511626240;
    mx[2].c[7] <== 1099511625984;
    mx[2].c[8] <== 1099511625728;
    mx[2].c[9] <== 1099511625472;
    mx[2].c[10] <== 1099511625216;
    mx[2].c[11] <== 1099511624960;
    mx[2].c[12] <== 1099511624704;
    mx[2].c[13] <== 1099511624448;
    mx[2].c[14] <== 1099511624192;
    mx[2].c[15] <== 1099511623936;
    mx[2].s[0] <== wbits.out[8];
    mx[2].s[1] <== wbits.out[9];
    mx[2].s[2] <== wbits.out[10];
    mx[2].s[3] <== wbits.out[11];
    em[2] = MulShift(S);   em[2].a <== acc[2];   em[2].b <== mx[2].out;   acc[3] <== em[2].out;
    mx[3] = Mux4();
    mx[3].c[0] <== 1099511627776;
    mx[3].c[1] <== 1099511623680;
    mx[3].c[2] <== 1099511619584;
    mx[3].c[3] <== 1099511615488;
    mx[3].c[4] <== 1099511611392;
    mx[3].c[5] <== 1099511607296;
    mx[3].c[6] <== 1099511603200;
    mx[3].c[7] <== 1099511599104;
    mx[3].c[8] <== 1099511595008;
    mx[3].c[9] <== 1099511590912;
    mx[3].c[10] <== 1099511586816;
    mx[3].c[11] <== 1099511582720;
    mx[3].c[12] <== 1099511578624;
    mx[3].c[13] <== 1099511574528;
    mx[3].c[14] <== 1099511570432;
    mx[3].c[15] <== 1099511566336;
    mx[3].s[0] <== wbits.out[12];
    mx[3].s[1] <== wbits.out[13];
    mx[3].s[2] <== wbits.out[14];
    mx[3].s[3] <== wbits.out[15];
    em[3] = MulShift(S);   em[3].a <== acc[3];   em[3].b <== mx[3].out;   acc[4] <== em[3].out;
    mx[4] = Mux4();
    mx[4].c[0] <== 1099511627776;
    mx[4].c[1] <== 1099511562240;
    mx[4].c[2] <== 1099511496704;
    mx[4].c[3] <== 1099511431168;
    mx[4].c[4] <== 1099511365632;
    mx[4].c[5] <== 1099511300096;
    mx[4].c[6] <== 1099511234560;
    mx[4].c[7] <== 1099511169024;
    mx[4].c[8] <== 1099511103488;
    mx[4].c[9] <== 1099511037952;
    mx[4].c[10] <== 1099510972416;
    mx[4].c[11] <== 1099510906880;
    mx[4].c[12] <== 1099510841344;
    mx[4].c[13] <== 1099510775808;
    mx[4].c[14] <== 1099510710272;
    mx[4].c[15] <== 1099510644736;
    mx[4].s[0] <== wbits.out[16];
    mx[4].s[1] <== wbits.out[17];
    mx[4].s[2] <== wbits.out[18];
    mx[4].s[3] <== wbits.out[19];
    em[4] = MulShift(S);   em[4].a <== acc[4];   em[4].b <== mx[4].out;   acc[5] <== em[4].out;
    mx[5] = Mux4();
    mx[5].c[0] <== 1099511627776;
    mx[5].c[1] <== 1099510579200;
    mx[5].c[2] <== 1099509530626;
    mx[5].c[3] <== 1099508482052;
    mx[5].c[4] <== 1099507433480;
    mx[5].c[5] <== 1099506384908;
    mx[5].c[6] <== 1099505336338;
    mx[5].c[7] <== 1099504287768;
    mx[5].c[8] <== 1099503239200;
    mx[5].c[9] <== 1099502190632;
    mx[5].c[10] <== 1099501142066;
    mx[5].c[11] <== 1099500093500;
    mx[5].c[12] <== 1099499044936;
    mx[5].c[13] <== 1099497996372;
    mx[5].c[14] <== 1099496947810;
    mx[5].c[15] <== 1099495899248;
    mx[5].s[0] <== wbits.out[20];
    mx[5].s[1] <== wbits.out[21];
    mx[5].s[2] <== wbits.out[22];
    mx[5].s[3] <== wbits.out[23];
    em[5] = MulShift(S);   em[5].a <== acc[5];   em[5].b <== mx[5].out;   acc[6] <== em[5].out;
    mx[6] = Mux4();
    mx[6].c[0] <== 1099511627776;
    mx[6].c[1] <== 1099494850688;
    mx[6].c[2] <== 1099478073856;
    mx[6].c[3] <== 1099461297280;
    mx[6].c[4] <== 1099444520960;
    mx[6].c[5] <== 1099427744896;
    mx[6].c[6] <== 1099410969088;
    mx[6].c[7] <== 1099394193536;
    mx[6].c[8] <== 1099377418240;
    mx[6].c[9] <== 1099360643200;
    mx[6].c[10] <== 1099343868415;
    mx[6].c[11] <== 1099327093887;
    mx[6].c[12] <== 1099310319615;
    mx[6].c[13] <== 1099293545599;
    mx[6].c[14] <== 1099276771838;
    mx[6].c[15] <== 1099259998334;
    mx[6].s[0] <== wbits.out[24];
    mx[6].s[1] <== wbits.out[25];
    mx[6].s[2] <== wbits.out[26];
    mx[6].s[3] <== wbits.out[27];
    em[6] = MulShift(S);   em[6].a <== acc[6];   em[6].b <== mx[6].out;   acc[7] <== em[6].out;
    mx[7] = Mux4();
    mx[7].c[0] <== 1099511627776;
    mx[7].c[1] <== 1099243225085;
    mx[7].c[2] <== 1098974887915;
    mx[7].c[3] <== 1098706616248;
    mx[7].c[4] <== 1098438410069;
    mx[7].c[5] <== 1098170269363;
    mx[7].c[6] <== 1097902194112;
    mx[7].c[7] <== 1097634184302;
    mx[7].c[8] <== 1097366239915;
    mx[7].c[9] <== 1097098360937;
    mx[7].c[10] <== 1096830547351;
    mx[7].c[11] <== 1096562799141;
    mx[7].c[12] <== 1096295116291;
    mx[7].c[13] <== 1096027498786;
    mx[7].c[14] <== 1095759946609;
    mx[7].c[15] <== 1095492459744;
    mx[7].s[0] <== wbits.out[28];
    mx[7].s[1] <== wbits.out[29];
    mx[7].s[2] <== wbits.out[30];
    mx[7].s[3] <== wbits.out[31];
    em[7] = MulShift(S);   em[7].a <== acc[7];   em[7].b <== mx[7].out;   acc[8] <== em[7].out;
    mx[8] = Mux4();
    mx[8].c[0] <== 1099511627776;
    mx[8].c[1] <== 1095225038176;
    mx[8].c[2] <== 1090955160405;
    mx[8].c[3] <== 1086701929310;
    mx[8].c[4] <== 1082465279991;
    mx[8].c[5] <== 1078245147803;
    mx[8].c[6] <== 1074041468351;
    mx[8].c[7] <== 1069854177493;
    mx[8].c[8] <== 1065683211334;
    mx[8].c[9] <== 1061528506231;
    mx[8].c[10] <== 1057389998788;
    mx[8].c[11] <== 1053267625857;
    mx[8].c[12] <== 1049161324534;
    mx[8].c[13] <== 1045071032164;
    mx[8].c[14] <== 1040996686332;
    mx[8].c[15] <== 1036938224869;
    mx[8].s[0] <== wbits.out[32];
    mx[8].s[1] <== wbits.out[33];
    mx[8].s[2] <== wbits.out[34];
    mx[8].s[3] <== wbits.out[35];
    em[8] = MulShift(S);   em[8].a <== acc[8];   em[8].b <== mx[8].out;   acc[9] <== em[8].out;
    mx[9] = Mux4();
    mx[9].c[0] <== 1099511627776;
    mx[9].c[1] <== 1032895585848;
    mx[9].c[2] <== 970315605868;
    mx[9].c[3] <== 911527155204;
    mx[9].c[4] <== 856300516708;
    mx[9].c[5] <== 804419891089;
    mx[9].c[6] <== 755682553676;
    mx[9].c[7] <== 709898062264;
    mx[9].c[8] <== 666887512957;
    mx[9].c[9] <== 626482841099;
    mx[9].c[10] <== 588526164557;
    mx[9].c[11] <== 552869166792;
    mx[9].c[12] <== 519372517311;
    mx[9].c[13] <== 487905327228;
    mx[9].c[14] <== 458344637815;
    mx[9].c[15] <== 430574940034;
    mx[9].s[0] <== wbits.out[36];
    mx[9].s[1] <== wbits.out[37];
    mx[9].s[2] <== wbits.out[38];
    mx[9].s[3] <== wbits.out[39];
    em[9] = MulShift(S);   em[9].a <== acc[9];   em[9].b <== mx[9].out;   acc[10] <== em[9].out;
    mx[10] = Mux4();
    mx[10].c[0] <== 1099511627776;
    mx[10].c[1] <== 404487723188;
    mx[10].c[2] <== 148802717567;
    mx[10].c[3] <== 54741460583;
    mx[10].c[4] <== 20138257928;
    mx[10].c[5] <== 7408451073;
    mx[10].c[6] <== 2725416841;
    mx[10].c[7] <== 1002624824;
    mx[10].c[8] <== 368845060;
    mx[10].c[9] <== 135690515;
    mx[10].c[10] <== 49917751;
    mx[10].c[11] <== 18363714;
    mx[10].c[12] <== 6755633;
    mx[10].c[13] <== 2485258;
    mx[10].c[14] <== 914275;
    mx[10].c[15] <== 336343;
    mx[10].s[0] <== wbits.out[40];
    mx[10].s[1] <== wbits.out[41];
    mx[10].s[2] <== wbits.out[42];
    mx[10].s[3] <== wbits.out[43];
    em[10] = MulShift(S);   em[10].a <== acc[10];   em[10].b <== mx[10].out;   acc[11] <== em[10].out;
    mx[11] = Mux4();
    mx[11].c[0] <== 1099511627776;
    mx[11].c[1] <== 123734;
    mx[11].c[2] <== 0;
    mx[11].c[3] <== 0;
    mx[11].c[4] <== 0;
    mx[11].c[5] <== 0;
    mx[11].c[6] <== 0;
    mx[11].c[7] <== 0;
    mx[11].c[8] <== 0;
    mx[11].c[9] <== 0;
    mx[11].c[10] <== 0;
    mx[11].c[11] <== 0;
    mx[11].c[12] <== 0;
    mx[11].c[13] <== 0;
    mx[11].c[14] <== 0;
    mx[11].c[15] <== 0;
    mx[11].s[0] <== wbits.out[44];
    mx[11].s[1] <== 0;
    mx[11].s[2] <== 0;
    mx[11].s[3] <== 0;
    em[11] = MulShift(S);   em[11].a <== acc[11];   em[11].b <== mx[11].out;   acc[12] <== em[11].out;
    signal eHat;
    eHat <== acc[12];

    // ---- Hart's two polynomials, Horner ----------------------------------------------------
    component bm[6];
    signal bh[7];
    bh[0] <== 38771525036;
    bm[0] = MulShift(S);   bm[0].a <== bh[0];   bm[0].b <== zc;   bh[1] <== bm[0].out + 770079323253;
    bm[1] = MulShift(S);   bm[1].a <== bh[1];   bm[1].b <== zc;   bh[2] <== bm[1].out + 7008245557788;
    bm[2] = MulShift(S);   bm[2].a <== bh[2];   bm[2].b <== zc;   bh[3] <== bm[2].out + 37287590584392;
    bm[3] = MulShift(S);   bm[3].a <== bh[3];   bm[3].b <== zc;   bh[4] <== bm[3].out + 123232484234805;
    bm[4] = MulShift(S);   bm[4].a <== bh[4];   bm[4].b <== zc;   bh[5] <== bm[4].out + 243226921210984;
    bm[5] = MulShift(S);   bm[5].a <== bh[5];   bm[5].b <== zc;   bh[6] <== bm[5].out + 242120011785791;
    component dm[7];
    signal dh[8];
    dh[0] <== 97184015999;
    dm[0] = MulShift(S);   dm[0].a <== dh[0];   dm[0].b <== zc;   dh[1] <== dm[0].out + 1930376460424;
    dm[1] = MulShift(S);   dm[1].a <== dh[1];   dm[1].b <== zc;   dh[2] <== dm[1].out + 17662750038997;
    dm[2] = MulShift(S);   dm[2].a <== dh[2];   dm[2].b <== zc;   dh[3] <== dm[2].out + 95416424124054;
    dm[3] = MulShift(S);   dm[3].a <== dh[3];   dm[3].b <== zc;   dh[4] <== dm[3].out + 326075839915906;
    dm[4] = MulShift(S);   dm[4].a <== dh[4];   dm[4].b <== zc;   dh[5] <== dm[4].out + 700755740672751;
    dm[5] = MulShift(S);   dm[5].a <== dh[5];   dm[5].b <== zc;   dh[6] <== dm[5].out + 872821480952553;
    dm[6] = MulShift(S);   dm[6].a <== dh[6];   dm[6].b <== zc;   dh[7] <== dm[6].out + 484240023571582;
    signal bHat;  signal dHat;
    bHat <== bh[6];
    dHat <== dh[7];

    // ---- c, the upper tail, and its relation to n -----------------------------------------
    // Hart returns the UPPER tail c and the CDF is c for x <= 0 and 1 - c for x > 0. Written as
    // one quadratic rather than a branch, since a circuit has no branches.
    signal cHat;
    cHat <== ONE - nHat + xSign * (2 * nHat - ONE);
    // c is an upper tail at |x| >= 0, so it never exceeds a half. Cheap, and it stops a prover
    // handing in the complement and letting the sign bit absorb it.
    component cLe = LessEqThan(S + 2);  cLe.in[0] <== cHat;  cLe.in[1] <== ONE \ 2;  cLe.out === 1;

    // c*d = e*b, which is the division without dividing. An absolute error of T ulp in c shows up
    // here as T*dHat, so the tolerance is TOLC*dHat and TOLC reads directly in ulp.
    // TOLC = 12, DERIVED in probe-ncdf-tol.mjs and not chosen: 19 ulp of accumulated exp error
    // times b/d <= 0.5, plus 3.4e-3 from b, 1.7e-3 from d, plus 1.0023 for this relation's own
    // floor remainder = 10.507 ulp worst, at z = 0. The real engine's worst leg uses 18.3% of it,
    // and gateB7-5 shows a value 13 ulp out IS refused — otherwise it is not a bound.
    signal lhs;   lhs <== cHat * dHat;
    signal eb;    eb  <== eHat * bHat;
    signal resid; resid <== computed * (lhs - eb);
    signal tolC;  tolC <== TOLC * dHat;
    signal cShift; cShift <== 2 * resid + tolC;
    // NO separate Num2Bits on cShift. LessEqThan(n) already decomposes in[0] + 2^n - in[1] into
    // n+1 bits, so a cShift that is out of range — including a field-wrapped negative one — makes
    // that decomposition unsatisfiable and the prover cannot produce a witness at all. The extra
    // check the sibling circuits carry can only turn an accept into a refusal, never the reverse,
    // and it costs NB_R constraints. gateB7-5 confirms the refusal by hand rather than trusting
    // this paragraph.
    component cOk = LessEqThan(NB_R); cOk.in[0] <== cShift; cOk.in[1] <== 2 * tolC; cOk.out === 1;

    // ---- the density, which the CDF has already computed ----------------------------------
    // phi(x) = e^{-x^2/2}/sqrt(2*pi), and e^{-x^2/2} is `eHat`, the exp intermediate above. So the
    // density costs one multiply. This matters more than it looks: df*phi(d1) is the factor that
    // CANCELS between any two greeks, which is what let the consistency identities exist without a
    // transcendental. Pinning it is what stops it cancelling.
    signal pd;    pd <== pHat * SQRT2PI;
    signal pe;    pe <== eHat * ONE;
    signal presid; presid <== computed * (pd - pe);
    signal tolP;  tolP <== TOLP * SQRT2PI;
    signal pShift; pShift <== 2 * presid + tolP;
    component pOk = LessEqThan(NB_P); pOk.in[0] <== pShift; pOk.in[1] <== 2 * tolP; pOk.out === 1;

    // ---- above the split, the bound ------------------------------------------------------
    // Both functions are decreasing on the tail, so their value AT the split is the maximum over
    // it. gateB7-5 measures the true maximum and refuses if either constant is under it.
    signal tailc;  tailc <== (1 - computed) * cHat;
    component tcOk = LessEqThan(S + 2); tcOk.in[0] <== tailc; tcOk.in[1] <== CDF_TAIL; tcOk.out === 1;
    signal tailp;  tailp <== (1 - computed) * pHat;
    component tpOk = LessEqThan(S + 2); tpOk.in[0] <== tailp; tpOk.in[1] <== PHI_TAIL; tpOk.out === 1;
}

component main {public [xSign, xMag, nHat, pHat]} = NormalCdf();
