pragma circom 2.1.6;

// GENERATED by zk/scripts/gen-ncdf-circom.mjs — do not hand-edit. Regenerate and re-gate.
//
// THE STANDARD NORMAL CDF, COMPUTED IN A CIRCUIT.
//
// The roadmap said options-risk "requires exp and erf in-circuit, which is where this stops being
// arithmetic and starts being a research project", and greeksfp/greekssigned/parity were built to
// route around it by proving CONSISTENCY identities that cancel the transcendental instead of
// evaluating it. probe-cdf-residue.mjs measured the cost of that route: a service using
// Abramowitz-Stegun 7.1.26 instead of Hart satisfies ALL EIGHT identities to 3.3e-14 and prices a
// leg 19.4% wrong. So the identities are blind to the thing that matters, and put-call parity is
// blind too — the put is P = df*(K*N(-d2) - F*N(-d1)), so any N with N(-x) = 1 - N(x) makes
// C - P = df*(F - K) hold ALGEBRAICALLY with N cancelling.
//
// The premise was wrong, in the same way the Tier-3 premise was wrong. "erf" is not what the
// engine computes. The engine computes HART (1968):
//
//     N(-z) = e^{-z^2/2} * b(z) / d(z)        for 0 <= z < 7.0711
//
// A ratio is a multiplication: c*d = e*b. A polynomial is Horner. That leaves one transcendental,
// e^{-w} — and e^{-w} FACTORS over the binary expansion of w in a way erf does not:
//
//     w = sum_i b_i 2^i    =>    e^{-w} = prod_i (e^{-2^i})^{b_i}
//
// Every factor is a constant and every choice is a multiplexer, so exp is a product of selected
// constants — which is what a circuit does natively. The wall was never the transcendental. It was
// the fixed-point representation, exactly as it was for Tier 3.
//
// ── WHAT IS PROVEN ──
//   for the public point x, the public value n is the normal CDF at x, and the public value p is
//   its density, both evaluated by the recurrences below. The evaluator is pinned, not asserted:
//   every multiply carries a range-checked remainder, so the prover cannot choose a rounding.
//
// ── WHAT IS NOT ──
//   this pins n GIVEN x. It does not pin x. For options-risk, x is d1 or d2, and pinning those
//   needs ln(F/K) — which is the same exp gadget run backwards (L is the log of F/K iff
//   K*exp(L) = F), so it is another instance of this block and not a new problem. NOT BUILT HERE.
//   What IS measured in gateB7-5: n and p together over-determine x, so a caller who binds p to a
//   published gamma and n to a published delta pins x without any logarithm at all.
//
// ── THE TAIL ──
//   Hart switches to a continued fraction at z = 7.0711. This circuit does NOT carry that branch.
//   Above the split it proves a BOUND instead: the upper tail is under 2 / 2^24, and the
//   density under 2 / 2^24. That is a real weakening and it is published as `computed`, so a
//   reader can see which of the two statements they were given. Measured over a listed-book shape,
//   1.03% of legs land there; over a one-hour-to-one-week wing, 46.79% do.
//
// ── SCALE ── every quantity is an integer at 2^-24. The truncating multiply
//   out * 2^S + rem = a * b,  0 <= rem < 2^S
//   is one constraint plus an S-bit range check, and it is the dominant cost: 26 of them.

include "../../node_modules/circomlib/circuits/bitify.circom";
include "../../node_modules/circomlib/circuits/comparators.circom";
include "../../node_modules/circomlib/circuits/mux4.circom";

// a * b >> S, with the discarded remainder range-checked so the prover cannot pick a rounding.
// Without the range check `out` is unconstrained below the S-th bit and the whole evaluator is
// decoration — the same failure the mantissa lower bound in greeksfp existed to prevent.
template MulShift(S) {
    signal input a;
    signal input b;
    signal output out;
    signal rem;
    signal prod;
    prod <== a * b;
    out <-- prod \ (1 << S);
    rem <-- prod % (1 << S);
    prod === out * (1 << S) + rem;
    component rb = Num2Bits(S);
    rb.in <== rem;
}

template NormalCdf() {
    var S      = 24;
    var ONE    = 16777216;                 // 1.0
    var NB_X   = 36;
    var NB_R   = 69;                       // derived: max(cHat*dHat, eHat*bHat) + 2, not rounded up
    var NB_P   = 52;
    var TOLC   = 12;                        // ulp; derived, see the block at the c relation
    var TOLP   = 10;
    var ZSPLIT = 118632832;      // 7.07106781186547, where Hart changes branch
    var SQRT2PI = 42054243;     // computed by Machin + integer sqrt, not quoted from a table
    var CDF_TAIL = 2;                   // N(-7.0711), the tail bound
    var PHI_TAIL = 2;                  // phi(7.0711), the density bound

    // ---- public interface -----------------------------------------------------------------
    signal input xSign;      // 0 when x >= 0, 1 when x < 0
    signal input xMag;       // |x| * 2^S
    signal input nHat;       // the claimed N(x) * 2^S
    signal input pHat;       // the claimed density phi(x) * 2^S

    signal output computed;  // 1 when the CDF was evaluated, 0 when only the tail bound was proven
    signal output tailC;     // the bound in force above the split, published so it is not implied
    signal output tailP;
    tailC <== CDF_TAIL;
    tailP <== PHI_TAIL;

    xSign * (xSign - 1) === 0;
    component rx = Num2Bits(NB_X);   rx.in <== xMag;
    component rn = Num2Bits(S + 1);  rn.in <== nHat;      // N is in [0,1], so S+1 bits is exact
    component rp = Num2Bits(S);      rp.in <== pHat;      // phi <= 0.3990 < 1
    component nLe = LessEqThan(S + 2); nLe.in[0] <== nHat; nLe.in[1] <== ONE; nLe.out === 1;

    // ---- which branch -------------------------------------------------------------------
    component split = LessThan(NB_X + 1);
    split.in[0] <== xMag;
    split.in[1] <== ZSPLIT;
    computed <== split.out;

    // The evaluator ALWAYS runs, on a clamped argument, so its own range checks can never be the
    // thing that fails on a tail input. Only the binding of its output to nHat/pHat is conditional.
    // Running it on the raw xMag instead would make W overflow at |x| = 386, which a real book
    // reaches, and the circuit would refuse where it means to bound.
    signal zc;
    zc <== xMag + (1 - computed) * (ZSPLIT - 1 - xMag);

    // ---- W = z^2 / 2, at 2^-S ------------------------------------------------------------
    signal sq;
    sq <== zc * zc;
    signal W;
    signal wRem;
    W    <-- sq \ (1 << 25);
    wRem <-- sq % (1 << 25);
    sq === W * (1 << 25) + wRem;
    component wrb = Num2Bits(25);  wrb.in <== wRem;
    component wbits = Num2Bits(29);  wbits.in <== W;

    // ---- e^{-W}: 8 groups of 4 bits, one Mux4 and one MulShift each -------------------------
    // 128 constants, generated at 200 fractional bits and re-derived by the gate.
    component mx[8];
    component em[8];
    signal acc[9];
    acc[0] <== ONE;
    mx[0] = Mux4();
    mx[0].c[0] <== 16777216;
    mx[0].c[1] <== 16777215;
    mx[0].c[2] <== 16777214;
    mx[0].c[3] <== 16777213;
    mx[0].c[4] <== 16777212;
    mx[0].c[5] <== 16777211;
    mx[0].c[6] <== 16777210;
    mx[0].c[7] <== 16777209;
    mx[0].c[8] <== 16777208;
    mx[0].c[9] <== 16777207;
    mx[0].c[10] <== 16777206;
    mx[0].c[11] <== 16777205;
    mx[0].c[12] <== 16777204;
    mx[0].c[13] <== 16777203;
    mx[0].c[14] <== 16777202;
    mx[0].c[15] <== 16777201;
    mx[0].s[0] <== wbits.out[0];
    mx[0].s[1] <== wbits.out[1];
    mx[0].s[2] <== wbits.out[2];
    mx[0].s[3] <== wbits.out[3];
    em[0] = MulShift(S);   em[0].a <== acc[0];   em[0].b <== mx[0].out;   acc[1] <== em[0].out;
    mx[1] = Mux4();
    mx[1].c[0] <== 16777216;
    mx[1].c[1] <== 16777200;
    mx[1].c[2] <== 16777184;
    mx[1].c[3] <== 16777168;
    mx[1].c[4] <== 16777152;
    mx[1].c[5] <== 16777136;
    mx[1].c[6] <== 16777120;
    mx[1].c[7] <== 16777104;
    mx[1].c[8] <== 16777088;
    mx[1].c[9] <== 16777072;
    mx[1].c[10] <== 16777056;
    mx[1].c[11] <== 16777040;
    mx[1].c[12] <== 16777024;
    mx[1].c[13] <== 16777008;
    mx[1].c[14] <== 16776992;
    mx[1].c[15] <== 16776976;
    mx[1].s[0] <== wbits.out[4];
    mx[1].s[1] <== wbits.out[5];
    mx[1].s[2] <== wbits.out[6];
    mx[1].s[3] <== wbits.out[7];
    em[1] = MulShift(S);   em[1].a <== acc[1];   em[1].b <== mx[1].out;   acc[2] <== em[1].out;
    mx[2] = Mux4();
    mx[2].c[0] <== 16777216;
    mx[2].c[1] <== 16776960;
    mx[2].c[2] <== 16776704;
    mx[2].c[3] <== 16776448;
    mx[2].c[4] <== 16776192;
    mx[2].c[5] <== 16775936;
    mx[2].c[6] <== 16775680;
    mx[2].c[7] <== 16775424;
    mx[2].c[8] <== 16775168;
    mx[2].c[9] <== 16774912;
    mx[2].c[10] <== 16774656;
    mx[2].c[11] <== 16774400;
    mx[2].c[12] <== 16774144;
    mx[2].c[13] <== 16773888;
    mx[2].c[14] <== 16773632;
    mx[2].c[15] <== 16773376;
    mx[2].s[0] <== wbits.out[8];
    mx[2].s[1] <== wbits.out[9];
    mx[2].s[2] <== wbits.out[10];
    mx[2].s[3] <== wbits.out[11];
    em[2] = MulShift(S);   em[2].a <== acc[2];   em[2].b <== mx[2].out;   acc[3] <== em[2].out;
    mx[3] = Mux4();
    mx[3].c[0] <== 16777216;
    mx[3].c[1] <== 16773120;
    mx[3].c[2] <== 16769026;
    mx[3].c[3] <== 16764932;
    mx[3].c[4] <== 16760840;
    mx[3].c[5] <== 16756748;
    mx[3].c[6] <== 16752658;
    mx[3].c[7] <== 16748568;
    mx[3].c[8] <== 16744480;
    mx[3].c[9] <== 16740392;
    mx[3].c[10] <== 16736306;
    mx[3].c[11] <== 16732220;
    mx[3].c[12] <== 16728136;
    mx[3].c[13] <== 16724052;
    mx[3].c[14] <== 16719970;
    mx[3].c[15] <== 16715888;
    mx[3].s[0] <== wbits.out[12];
    mx[3].s[1] <== wbits.out[13];
    mx[3].s[2] <== wbits.out[14];
    mx[3].s[3] <== wbits.out[15];
    em[3] = MulShift(S);   em[3].a <== acc[3];   em[3].b <== mx[3].out;   acc[4] <== em[3].out;
    mx[4] = Mux4();
    mx[4].c[0] <== 16777216;
    mx[4].c[1] <== 16711808;
    mx[4].c[2] <== 16646655;
    mx[4].c[3] <== 16581756;
    mx[4].c[4] <== 16517109;
    mx[4].c[5] <== 16452715;
    mx[4].c[6] <== 16388572;
    mx[4].c[7] <== 16324679;
    mx[4].c[8] <== 16261035;
    mx[4].c[9] <== 16197640;
    mx[4].c[10] <== 16134491;
    mx[4].c[11] <== 16071589;
    mx[4].c[12] <== 16008931;
    mx[4].c[13] <== 15946518;
    mx[4].c[14] <== 15884349;
    mx[4].c[15] <== 15822422;
    mx[4].s[0] <== wbits.out[16];
    mx[4].s[1] <== wbits.out[17];
    mx[4].s[2] <== wbits.out[18];
    mx[4].s[3] <== wbits.out[19];
    em[4] = MulShift(S);   em[4].a <== acc[4];   em[4].b <== mx[4].out;   acc[5] <== em[4].out;
    mx[5] = Mux4();
    mx[5].c[0] <== 16777216;
    mx[5].c[1] <== 15760736;
    mx[5].c[2] <== 14805841;
    mx[5].c[3] <== 13908801;
    mx[5].c[4] <== 13066109;
    mx[5].c[5] <== 12274473;
    mx[5].c[6] <== 11530801;
    mx[5].c[7] <== 10832185;
    mx[5].c[8] <== 10175896;
    mx[5].c[9] <== 9559370;
    mx[5].c[10] <== 8980197;
    mx[5].c[11] <== 8436114;
    mx[5].c[12] <== 7924996;
    mx[5].c[13] <== 7444844;
    mx[5].c[14] <== 6993784;
    mx[5].c[15] <== 6570052;
    mx[5].s[0] <== wbits.out[20];
    mx[5].s[1] <== wbits.out[21];
    mx[5].s[2] <== wbits.out[22];
    mx[5].s[3] <== wbits.out[23];
    em[5] = MulShift(S);   em[5].a <== acc[5];   em[5].b <== mx[5].out;   acc[6] <== em[5].out;
    mx[6] = Mux4();
    mx[6].c[0] <== 16777216;
    mx[6].c[1] <== 6171993;
    mx[6].c[2] <== 2270549;
    mx[6].c[3] <== 835288;
    mx[6].c[4] <== 307285;
    mx[6].c[5] <== 113044;
    mx[6].c[6] <== 41587;
    mx[6].c[7] <== 15299;
    mx[6].c[8] <== 5628;
    mx[6].c[9] <== 2070;
    mx[6].c[10] <== 762;
    mx[6].c[11] <== 280;
    mx[6].c[12] <== 103;
    mx[6].c[13] <== 38;
    mx[6].c[14] <== 14;
    mx[6].c[15] <== 5;
    mx[6].s[0] <== wbits.out[24];
    mx[6].s[1] <== wbits.out[25];
    mx[6].s[2] <== wbits.out[26];
    mx[6].s[3] <== wbits.out[27];
    em[6] = MulShift(S);   em[6].a <== acc[6];   em[6].b <== mx[6].out;   acc[7] <== em[6].out;
    mx[7] = Mux4();
    mx[7].c[0] <== 16777216;
    mx[7].c[1] <== 2;
    mx[7].c[2] <== 0;
    mx[7].c[3] <== 0;
    mx[7].c[4] <== 0;
    mx[7].c[5] <== 0;
    mx[7].c[6] <== 0;
    mx[7].c[7] <== 0;
    mx[7].c[8] <== 0;
    mx[7].c[9] <== 0;
    mx[7].c[10] <== 0;
    mx[7].c[11] <== 0;
    mx[7].c[12] <== 0;
    mx[7].c[13] <== 0;
    mx[7].c[14] <== 0;
    mx[7].c[15] <== 0;
    mx[7].s[0] <== wbits.out[28];
    mx[7].s[1] <== 0;
    mx[7].s[2] <== 0;
    mx[7].s[3] <== 0;
    em[7] = MulShift(S);   em[7].a <== acc[7];   em[7].b <== mx[7].out;   acc[8] <== em[7].out;
    signal eHat;
    eHat <== acc[8];

    // ---- Hart's two polynomials, Horner ----------------------------------------------------
    component bm[6];
    signal bh[7];
    bh[0] <== 591607;
    bm[0] = MulShift(S);   bm[0].a <== bh[0];   bm[0].b <== zc;   bh[1] <== bm[0].out + 11750478;
    bm[1] = MulShift(S);   bm[1].a <== bh[1];   bm[1].b <== zc;   bh[2] <== bm[1].out + 106937341;
    bm[2] = MulShift(S);   bm[2].a <== bh[2];   bm[2].b <== zc;   bh[3] <== bm[2].out + 568963479;
    bm[3] = MulShift(S);   bm[3].a <== bh[3];   bm[3].b <== zc;   bh[4] <== bm[3].out + 1880378483;
    bm[4] = MulShift(S);   bm[4].a <== bh[4];   bm[4].b <== zc;   bh[5] <== bm[4].out + 3711348285;
    bm[5] = MulShift(S);   bm[5].a <== bh[5];   bm[5].b <== zc;   bh[6] <== bm[5].out + 3694458188;
    component dm[7];
    signal dh[8];
    dh[0] <== 1482910;
    dm[0] = MulShift(S);   dm[0].a <== dh[0];   dm[0].b <== zc;   dh[1] <== dm[0].out + 29455207;
    dm[1] = MulShift(S);   dm[1].a <== dh[1];   dm[1].b <== zc;   dh[2] <== dm[1].out + 269512177;
    dm[2] = MulShift(S);   dm[2].a <== dh[2];   dm[2].b <== zc;   dh[3] <== dm[2].out + 1455939089;
    dm[3] = MulShift(S);   dm[3].a <== dh[3];   dm[3].b <== zc;   dh[4] <== dm[3].out + 4975522460;
    dm[4] = MulShift(S);   dm[4].a <== dh[4];   dm[4].b <== zc;   dh[5] <== dm[4].out + 10692684031;
    dm[5] = MulShift(S);   dm[5].a <== dh[5];   dm[5].b <== zc;   dh[6] <== dm[5].out + 13318198867;
    dm[6] = MulShift(S);   dm[6].a <== dh[6];   dm[6].b <== zc;   dh[7] <== dm[6].out + 7388916375;
    signal bHat;  signal dHat;
    bHat <== bh[6];
    dHat <== dh[7];

    // ---- c, the upper tail, and its relation to n -----------------------------------------
    // Hart returns the UPPER tail c and the CDF is c for x <= 0 and 1 - c for x > 0. Written as
    // one quadratic rather than a branch, since a circuit has no branches.
    signal cHat;
    cHat <== ONE - nHat + xSign * (2 * nHat - ONE);
    // c is an upper tail at |x| >= 0, so it never exceeds a half. Cheap, and it stops a prover
    // handing in the complement and letting the sign bit absorb it.
    component cLe = LessEqThan(S + 2);  cLe.in[0] <== cHat;  cLe.in[1] <== ONE \ 2;  cLe.out === 1;

    // c*d = e*b, which is the division without dividing. An absolute error of T ulp in c shows up
    // here as T*dHat, so the tolerance is TOLC*dHat and TOLC reads directly in ulp.
    // TOLC = 12, DERIVED in probe-ncdf-tol.mjs and not chosen: 19 ulp of accumulated exp error
    // times b/d <= 0.5, plus 3.4e-3 from b, 1.7e-3 from d, plus 1.0023 for this relation's own
    // floor remainder = 10.507 ulp worst, at z = 0. The real engine's worst leg uses 18.3% of it,
    // and gateB7-5 shows a value 13 ulp out IS refused — otherwise it is not a bound.
    signal lhs;   lhs <== cHat * dHat;
    signal eb;    eb  <== eHat * bHat;
    signal resid; resid <== computed * (lhs - eb);
    signal tolC;  tolC <== TOLC * dHat;
    signal cShift; cShift <== 2 * resid + tolC;
    // NO separate Num2Bits on cShift. LessEqThan(n) already decomposes in[0] + 2^n - in[1] into
    // n+1 bits, so a cShift that is out of range — including a field-wrapped negative one — makes
    // that decomposition unsatisfiable and the prover cannot produce a witness at all. The extra
    // check the sibling circuits carry can only turn an accept into a refusal, never the reverse,
    // and it costs NB_R constraints. gateB7-5 confirms the refusal by hand rather than trusting
    // this paragraph.
    component cOk = LessEqThan(NB_R); cOk.in[0] <== cShift; cOk.in[1] <== 2 * tolC; cOk.out === 1;

    // ---- the density, which the CDF has already computed ----------------------------------
    // phi(x) = e^{-x^2/2}/sqrt(2*pi), and e^{-x^2/2} is `eHat`, the exp intermediate above. So the
    // density costs one multiply. This matters more than it looks: df*phi(d1) is the factor that
    // CANCELS between any two greeks, which is what let the consistency identities exist without a
    // transcendental. Pinning it is what stops it cancelling.
    signal pd;    pd <== pHat * SQRT2PI;
    signal pe;    pe <== eHat * ONE;
    signal presid; presid <== computed * (pd - pe);
    signal tolP;  tolP <== TOLP * SQRT2PI;
    signal pShift; pShift <== 2 * presid + tolP;
    component pOk = LessEqThan(NB_P); pOk.in[0] <== pShift; pOk.in[1] <== 2 * tolP; pOk.out === 1;

    // ---- above the split, the bound ------------------------------------------------------
    // Both functions are decreasing on the tail, so their value AT the split is the maximum over
    // it. gateB7-5 measures the true maximum and refuses if either constant is under it.
    signal tailc;  tailc <== (1 - computed) * cHat;
    component tcOk = LessEqThan(S + 2); tcOk.in[0] <== tailc; tcOk.in[1] <== CDF_TAIL; tcOk.out === 1;
    signal tailp;  tailp <== (1 - computed) * pHat;
    component tpOk = LessEqThan(S + 2); tpOk.in[0] <== tailp; tpOk.in[1] <== PHI_TAIL; tpOk.out === 1;
}

component main {public [xSign, xMag, nHat, pHat]} = NormalCdf();
