pragma circom 2.1.6;

// GENERATED by zk/scripts/gen-ncdf-circom.mjs — do not hand-edit. Regenerate and re-gate.
//
// THE STANDARD NORMAL CDF, COMPUTED IN A CIRCUIT.
//
// The roadmap said options-risk "requires exp and erf in-circuit, which is where this stops being
// arithmetic and starts being a research project", and greeksfp/greekssigned/parity were built to
// route around it by proving CONSISTENCY identities that cancel the transcendental instead of
// evaluating it. probe-cdf-residue.mjs measured the cost of that route: a service using
// Abramowitz-Stegun 7.1.26 instead of Hart satisfies ALL EIGHT identities to 3.3e-14 and prices a
// leg 19.4% wrong. So the identities are blind to the thing that matters, and put-call parity is
// blind too — the put is P = df*(K*N(-d2) - F*N(-d1)), so any N with N(-x) = 1 - N(x) makes
// C - P = df*(F - K) hold ALGEBRAICALLY with N cancelling.
//
// The premise was wrong, in the same way the Tier-3 premise was wrong. "erf" is not what the
// engine computes. The engine computes HART (1968):
//
//     N(-z) = e^{-z^2/2} * b(z) / d(z)        for 0 <= z < 7.0711
//
// A ratio is a multiplication: c*d = e*b. A polynomial is Horner. That leaves one transcendental,
// e^{-w} — and e^{-w} FACTORS over the binary expansion of w in a way erf does not:
//
//     w = sum_i b_i 2^i    =>    e^{-w} = prod_i (e^{-2^i})^{b_i}
//
// Every factor is a constant and every choice is a multiplexer, so exp is a product of selected
// constants — which is what a circuit does natively. The wall was never the transcendental. It was
// the fixed-point representation, exactly as it was for Tier 3.
//
// ── WHAT IS PROVEN ──
//   for the public point x, the public value n is the normal CDF at x, and the public value p is
//   its density, both evaluated by the recurrences below. The evaluator is pinned, not asserted:
//   every multiply carries a range-checked remainder, so the prover cannot choose a rounding.
//
// ── WHAT IS NOT ──
//   this pins n GIVEN x. It does not pin x. For options-risk, x is d1 or d2, and pinning those
//   needs ln(F/K) — which is the same exp gadget run backwards (L is the log of F/K iff
//   K*exp(L) = F), so it is another instance of this block and not a new problem. NOT BUILT HERE.
//   What IS measured in gateB7-5: n and p together over-determine x, so a caller who binds p to a
//   published gamma and n to a published delta pins x without any logarithm at all.
//
// ── THE TAIL ──
//   Hart switches to a continued fraction at z = 7.0711. This circuit does NOT carry that branch.
//   Above the split it proves a BOUND instead: the upper tail is under 2 / 2^28, and the
//   density under 2 / 2^28. That is a real weakening and it is published as `computed`, so a
//   reader can see which of the two statements they were given. Measured over a listed-book shape,
//   1.03% of legs land there; over a one-hour-to-one-week wing, 46.79% do.
//
// ── SCALE ── every quantity is an integer at 2^-28. The truncating multiply
//   out * 2^S + rem = a * b,  0 <= rem < 2^S
//   is one constraint plus an S-bit range check, and it is the dominant cost: 26 of them.

include "../../node_modules/circomlib/circuits/bitify.circom";
include "../../node_modules/circomlib/circuits/comparators.circom";
include "../../node_modules/circomlib/circuits/mux4.circom";

// a * b >> S, with the discarded remainder range-checked so the prover cannot pick a rounding.
// Without the range check `out` is unconstrained below the S-th bit and the whole evaluator is
// decoration — the same failure the mantissa lower bound in greeksfp existed to prevent.
template MulShift(S) {
    signal input a;
    signal input b;
    signal output out;
    signal rem;
    signal prod;
    prod <== a * b;
    out <-- prod \ (1 << S);
    rem <-- prod % (1 << S);
    prod === out * (1 << S) + rem;
    component rb = Num2Bits(S);
    rb.in <== rem;
}

template NormalCdf() {
    var S      = 28;
    var ONE    = 268435456;                 // 1.0
    var NB_X   = 40;
    var NB_R   = 77;                       // derived: max(cHat*dHat, eHat*bHat) + 2, not rounded up
    var NB_P   = 60;
    var TOLC   = 12;                        // ulp; derived, see the block at the c relation
    var TOLP   = 10;
    var ZSPLIT = 1898125312;      // 7.07106781186547, where Hart changes branch
    var SQRT2PI = 672867903;     // computed by Machin + integer sqrt, not quoted from a table
    var CDF_TAIL = 2;                   // N(-7.0711), the tail bound
    var PHI_TAIL = 2;                  // phi(7.0711), the density bound

    // ---- public interface -----------------------------------------------------------------
    signal input xSign;      // 0 when x >= 0, 1 when x < 0
    signal input xMag;       // |x| * 2^S
    signal input nHat;       // the claimed N(x) * 2^S
    signal input pHat;       // the claimed density phi(x) * 2^S

    signal output computed;  // 1 when the CDF was evaluated, 0 when only the tail bound was proven
    signal output tailC;     // the bound in force above the split, published so it is not implied
    signal output tailP;
    tailC <== CDF_TAIL;
    tailP <== PHI_TAIL;

    xSign * (xSign - 1) === 0;
    component rx = Num2Bits(NB_X);   rx.in <== xMag;
    component rn = Num2Bits(S + 1);  rn.in <== nHat;      // N is in [0,1], so S+1 bits is exact
    component rp = Num2Bits(S);      rp.in <== pHat;      // phi <= 0.3990 < 1
    component nLe = LessEqThan(S + 2); nLe.in[0] <== nHat; nLe.in[1] <== ONE; nLe.out === 1;

    // ---- which branch -------------------------------------------------------------------
    component split = LessThan(NB_X + 1);
    split.in[0] <== xMag;
    split.in[1] <== ZSPLIT;
    computed <== split.out;

    // The evaluator ALWAYS runs, on a clamped argument, so its own range checks can never be the
    // thing that fails on a tail input. Only the binding of its output to nHat/pHat is conditional.
    // Running it on the raw xMag instead would make W overflow at |x| = 386, which a real book
    // reaches, and the circuit would refuse where it means to bound.
    signal zc;
    zc <== xMag + (1 - computed) * (ZSPLIT - 1 - xMag);

    // ---- W = z^2 / 2, at 2^-S ------------------------------------------------------------
    signal sq;
    sq <== zc * zc;
    signal W;
    signal wRem;
    W    <-- sq \ (1 << 29);
    wRem <-- sq % (1 << 29);
    sq === W * (1 << 29) + wRem;
    component wrb = Num2Bits(29);  wrb.in <== wRem;
    component wbits = Num2Bits(33);  wbits.in <== W;

    // ---- e^{-W}: 9 groups of 4 bits, one Mux4 and one MulShift each -------------------------
    // 144 constants, generated at 200 fractional bits and re-derived by the gate.
    component mx[9];
    component em[9];
    signal acc[10];
    acc[0] <== ONE;
    mx[0] = Mux4();
    mx[0].c[0] <== 268435456;
    mx[0].c[1] <== 268435455;
    mx[0].c[2] <== 268435454;
    mx[0].c[3] <== 268435453;
    mx[0].c[4] <== 268435452;
    mx[0].c[5] <== 268435451;
    mx[0].c[6] <== 268435450;
    mx[0].c[7] <== 268435449;
    mx[0].c[8] <== 268435448;
    mx[0].c[9] <== 268435447;
    mx[0].c[10] <== 268435446;
    mx[0].c[11] <== 268435445;
    mx[0].c[12] <== 268435444;
    mx[0].c[13] <== 268435443;
    mx[0].c[14] <== 268435442;
    mx[0].c[15] <== 268435441;
    mx[0].s[0] <== wbits.out[0];
    mx[0].s[1] <== wbits.out[1];
    mx[0].s[2] <== wbits.out[2];
    mx[0].s[3] <== wbits.out[3];
    em[0] = MulShift(S);   em[0].a <== acc[0];   em[0].b <== mx[0].out;   acc[1] <== em[0].out;
    mx[1] = Mux4();
    mx[1].c[0] <== 268435456;
    mx[1].c[1] <== 268435440;
    mx[1].c[2] <== 268435424;
    mx[1].c[3] <== 268435408;
    mx[1].c[4] <== 268435392;
    mx[1].c[5] <== 268435376;
    mx[1].c[6] <== 268435360;
    mx[1].c[7] <== 268435344;
    mx[1].c[8] <== 268435328;
    mx[1].c[9] <== 268435312;
    mx[1].c[10] <== 268435296;
    mx[1].c[11] <== 268435280;
    mx[1].c[12] <== 268435264;
    mx[1].c[13] <== 268435248;
    mx[1].c[14] <== 268435232;
    mx[1].c[15] <== 268435216;
    mx[1].s[0] <== wbits.out[4];
    mx[1].s[1] <== wbits.out[5];
    mx[1].s[2] <== wbits.out[6];
    mx[1].s[3] <== wbits.out[7];
    em[1] = MulShift(S);   em[1].a <== acc[1];   em[1].b <== mx[1].out;   acc[2] <== em[1].out;
    mx[2] = Mux4();
    mx[2].c[0] <== 268435456;
    mx[2].c[1] <== 268435200;
    mx[2].c[2] <== 268434944;
    mx[2].c[3] <== 268434688;
    mx[2].c[4] <== 268434432;
    mx[2].c[5] <== 268434176;
    mx[2].c[6] <== 268433920;
    mx[2].c[7] <== 268433664;
    mx[2].c[8] <== 268433408;
    mx[2].c[9] <== 268433152;
    mx[2].c[10] <== 268432896;
    mx[2].c[11] <== 268432640;
    mx[2].c[12] <== 268432384;
    mx[2].c[13] <== 268432128;
    mx[2].c[14] <== 268431872;
    mx[2].c[15] <== 268431616;
    mx[2].s[0] <== wbits.out[8];
    mx[2].s[1] <== wbits.out[9];
    mx[2].s[2] <== wbits.out[10];
    mx[2].s[3] <== wbits.out[11];
    em[2] = MulShift(S);   em[2].a <== acc[2];   em[2].b <== mx[2].out;   acc[3] <== em[2].out;
    mx[3] = Mux4();
    mx[3].c[0] <== 268435456;
    mx[3].c[1] <== 268431360;
    mx[3].c[2] <== 268427264;
    mx[3].c[3] <== 268423168;
    mx[3].c[4] <== 268419072;
    mx[3].c[5] <== 268414977;
    mx[3].c[6] <== 268410881;
    mx[3].c[7] <== 268406786;
    mx[3].c[8] <== 268402690;
    mx[3].c[9] <== 268398595;
    mx[3].c[10] <== 268394499;
    mx[3].c[11] <== 268390404;
    mx[3].c[12] <== 268386308;
    mx[3].c[13] <== 268382213;
    mx[3].c[14] <== 268378118;
    mx[3].c[15] <== 268374023;
    mx[3].s[0] <== wbits.out[12];
    mx[3].s[1] <== wbits.out[13];
    mx[3].s[2] <== wbits.out[14];
    mx[3].s[3] <== wbits.out[15];
    em[3] = MulShift(S);   em[3].a <== acc[3];   em[3].b <== mx[3].out;   acc[4] <== em[3].out;
    mx[4] = Mux4();
    mx[4].c[0] <== 268435456;
    mx[4].c[1] <== 268369928;
    mx[4].c[2] <== 268304416;
    mx[4].c[3] <== 268238920;
    mx[4].c[4] <== 268173440;
    mx[4].c[5] <== 268107976;
    mx[4].c[6] <== 268042528;
    mx[4].c[7] <== 267977096;
    mx[4].c[8] <== 267911680;
    mx[4].c[9] <== 267846280;
    mx[4].c[10] <== 267780895;
    mx[4].c[11] <== 267715527;
    mx[4].c[12] <== 267650175;
    mx[4].c[13] <== 267584839;
    mx[4].c[14] <== 267519518;
    mx[4].c[15] <== 267454214;
    mx[4].s[0] <== wbits.out[16];
    mx[4].s[1] <== wbits.out[17];
    mx[4].s[2] <== wbits.out[18];
    mx[4].s[3] <== wbits.out[19];
    em[4] = MulShift(S);   em[4].a <== acc[4];   em[4].b <== mx[4].out;   acc[5] <== em[4].out;
    mx[5] = Mux4();
    mx[5].c[0] <== 268435456;
    mx[5].c[1] <== 267388925;
    mx[5].c[2] <== 266346475;
    mx[5].c[3] <== 265308088;
    mx[5].c[4] <== 264273750;
    mx[5].c[5] <== 263243444;
    mx[5].c[6] <== 262217155;
    mx[5].c[7] <== 261194868;
    mx[5].c[8] <== 260176565;
    mx[5].c[9] <== 259162233;
    mx[5].c[10] <== 258151855;
    mx[5].c[11] <== 257145416;
    mx[5].c[12] <== 256142901;
    mx[5].c[13] <== 255144295;
    mx[5].c[14] <== 254149582;
    mx[5].c[15] <== 253158746;
    mx[5].s[0] <== wbits.out[20];
    mx[5].s[1] <== wbits.out[21];
    mx[5].s[2] <== wbits.out[22];
    mx[5].s[3] <== wbits.out[23];
    em[5] = MulShift(S);   em[5].a <== acc[5];   em[5].b <== mx[5].out;   acc[6] <== em[5].out;
    mx[6] = Mux4();
    mx[6].c[0] <== 268435456;
    mx[6].c[1] <== 252171774;
    mx[6].c[2] <== 236893458;
    mx[6].c[3] <== 222540809;
    mx[6].c[4] <== 209057743;
    mx[6].c[5] <== 196391575;
    mx[6].c[6] <== 184492811;
    mx[6].c[7] <== 173314957;
    mx[6].c[8] <== 162814334;
    mx[6].c[9] <== 152949912;
    mx[6].c[10] <== 143683146;
    mx[6].c[11] <== 134977824;
    mx[6].c[12] <== 126799931;
    mx[6].c[13] <== 119117512;
    mx[6].c[14] <== 111900546;
    mx[6].c[15] <== 105120835;
    mx[6].s[0] <== wbits.out[24];
    mx[6].s[1] <== wbits.out[25];
    mx[6].s[2] <== wbits.out[26];
    mx[6].s[3] <== wbits.out[27];
    em[6] = MulShift(S);   em[6].a <== acc[6];   em[6].b <== mx[6].out;   acc[7] <== em[6].out;
    mx[7] = Mux4();
    mx[7].c[0] <== 268435456;
    mx[7].c[1] <== 98751886;
    mx[7].c[2] <== 36328788;
    mx[7].c[3] <== 13364614;
    mx[7].c[4] <== 4916567;
    mx[7].c[5] <== 1808704;
    mx[7].c[6] <== 665385;
    mx[7].c[7] <== 244781;
    mx[7].c[8] <== 90050;
    mx[7].c[9] <== 33128;
    mx[7].c[10] <== 12187;
    mx[7].c[11] <== 4483;
    mx[7].c[12] <== 1649;
    mx[7].c[13] <== 607;
    mx[7].c[14] <== 223;
    mx[7].c[15] <== 82;
    mx[7].s[0] <== wbits.out[28];
    mx[7].s[1] <== wbits.out[29];
    mx[7].s[2] <== wbits.out[30];
    mx[7].s[3] <== wbits.out[31];
    em[7] = MulShift(S);   em[7].a <== acc[7];   em[7].b <== mx[7].out;   acc[8] <== em[7].out;
    mx[8] = Mux4();
    mx[8].c[0] <== 268435456;
    mx[8].c[1] <== 30;
    mx[8].c[2] <== 0;
    mx[8].c[3] <== 0;
    mx[8].c[4] <== 0;
    mx[8].c[5] <== 0;
    mx[8].c[6] <== 0;
    mx[8].c[7] <== 0;
    mx[8].c[8] <== 0;
    mx[8].c[9] <== 0;
    mx[8].c[10] <== 0;
    mx[8].c[11] <== 0;
    mx[8].c[12] <== 0;
    mx[8].c[13] <== 0;
    mx[8].c[14] <== 0;
    mx[8].c[15] <== 0;
    mx[8].s[0] <== wbits.out[32];
    mx[8].s[1] <== 0;
    mx[8].s[2] <== 0;
    mx[8].s[3] <== 0;
    em[8] = MulShift(S);   em[8].a <== acc[8];   em[8].b <== mx[8].out;   acc[9] <== em[8].out;
    signal eHat;
    eHat <== acc[9];

    // ---- Hart's two polynomials, Horner ----------------------------------------------------
    component bm[6];
    signal bh[7];
    bh[0] <== 9465704;
    bm[0] = MulShift(S);   bm[0].a <== bh[0];   bm[0].b <== zc;   bh[1] <== bm[0].out + 188007647;
    bm[1] = MulShift(S);   bm[1].a <== bh[1];   bm[1].b <== zc;   bh[2] <== bm[1].out + 1710997451;
    bm[2] = MulShift(S);   bm[2].a <== bh[2];   bm[2].b <== zc;   bh[3] <== bm[2].out + 9103415670;
    bm[3] = MulShift(S);   bm[3].a <== bh[3];   bm[3].b <== zc;   bh[4] <== bm[3].out + 30086055721;
    bm[4] = MulShift(S);   bm[4].a <== bh[4];   bm[4].b <== zc;   bh[5] <== bm[4].out + 59381572561;
    bm[5] = MulShift(S);   bm[5].a <== bh[5];   bm[5].b <== zc;   bh[6] <== bm[5].out + 59111331002;
    component dm[7];
    signal dh[8];
    dh[0] <== 23726566;
    dm[0] = MulShift(S);   dm[0].a <== dh[0];   dm[0].b <== zc;   dh[1] <== dm[0].out + 471283316;
    dm[1] = MulShift(S);   dm[1].a <== dh[1];   dm[1].b <== zc;   dh[2] <== dm[1].out + 4312194834;
    dm[2] = MulShift(S);   dm[2].a <== dh[2];   dm[2].b <== zc;   dh[3] <== dm[2].out + 23295025421;
    dm[3] = MulShift(S);   dm[3].a <== dh[3];   dm[3].b <== zc;   dh[4] <== dm[3].out + 79608359354;
    dm[4] = MulShift(S);   dm[4].a <== dh[4];   dm[4].b <== zc;   dh[5] <== dm[4].out + 171082944500;
    dm[5] = MulShift(S);   dm[5].a <== dh[5];   dm[5].b <== zc;   dh[6] <== dm[5].out + 213091181873;
    dm[6] = MulShift(S);   dm[6].a <== dh[6];   dm[6].b <== zc;   dh[7] <== dm[6].out + 118222662005;
    signal bHat;  signal dHat;
    bHat <== bh[6];
    dHat <== dh[7];

    // ---- c, the upper tail, and its relation to n -----------------------------------------
    // Hart returns the UPPER tail c and the CDF is c for x <= 0 and 1 - c for x > 0. Written as
    // one quadratic rather than a branch, since a circuit has no branches.
    signal cHat;
    cHat <== ONE - nHat + xSign * (2 * nHat - ONE);
    // c is an upper tail at |x| >= 0, so it never exceeds a half. Cheap, and it stops a prover
    // handing in the complement and letting the sign bit absorb it.
    component cLe = LessEqThan(S + 2);  cLe.in[0] <== cHat;  cLe.in[1] <== ONE \ 2;  cLe.out === 1;

    // c*d = e*b, which is the division without dividing. An absolute error of T ulp in c shows up
    // here as T*dHat, so the tolerance is TOLC*dHat and TOLC reads directly in ulp.
    // TOLC = 12, DERIVED in probe-ncdf-tol.mjs and not chosen: 19 ulp of accumulated exp error
    // times b/d <= 0.5, plus 3.4e-3 from b, 1.7e-3 from d, plus 1.0023 for this relation's own
    // floor remainder = 10.507 ulp worst, at z = 0. The real engine's worst leg uses 18.3% of it,
    // and gateB7-5 shows a value 13 ulp out IS refused — otherwise it is not a bound.
    signal lhs;   lhs <== cHat * dHat;
    signal eb;    eb  <== eHat * bHat;
    signal resid; resid <== computed * (lhs - eb);
    signal tolC;  tolC <== TOLC * dHat;
    signal cShift; cShift <== 2 * resid + tolC;
    // NO separate Num2Bits on cShift. LessEqThan(n) already decomposes in[0] + 2^n - in[1] into
    // n+1 bits, so a cShift that is out of range — including a field-wrapped negative one — makes
    // that decomposition unsatisfiable and the prover cannot produce a witness at all. The extra
    // check the sibling circuits carry can only turn an accept into a refusal, never the reverse,
    // and it costs NB_R constraints. gateB7-5 confirms the refusal by hand rather than trusting
    // this paragraph.
    component cOk = LessEqThan(NB_R); cOk.in[0] <== cShift; cOk.in[1] <== 2 * tolC; cOk.out === 1;

    // ---- the density, which the CDF has already computed ----------------------------------
    // phi(x) = e^{-x^2/2}/sqrt(2*pi), and e^{-x^2/2} is `eHat`, the exp intermediate above. So the
    // density costs one multiply. This matters more than it looks: df*phi(d1) is the factor that
    // CANCELS between any two greeks, which is what let the consistency identities exist without a
    // transcendental. Pinning it is what stops it cancelling.
    signal pd;    pd <== pHat * SQRT2PI;
    signal pe;    pe <== eHat * ONE;
    signal presid; presid <== computed * (pd - pe);
    signal tolP;  tolP <== TOLP * SQRT2PI;
    signal pShift; pShift <== 2 * presid + tolP;
    component pOk = LessEqThan(NB_P); pOk.in[0] <== pShift; pOk.in[1] <== 2 * tolP; pOk.out === 1;

    // ---- above the split, the bound ------------------------------------------------------
    // Both functions are decreasing on the tail, so their value AT the split is the maximum over
    // it. gateB7-5 measures the true maximum and refuses if either constant is under it.
    signal tailc;  tailc <== (1 - computed) * cHat;
    component tcOk = LessEqThan(S + 2); tcOk.in[0] <== tailc; tcOk.in[1] <== CDF_TAIL; tcOk.out === 1;
    signal tailp;  tailp <== (1 - computed) * pHat;
    component tpOk = LessEqThan(S + 2); tpOk.in[0] <== tailp; tpOk.in[1] <== PHI_TAIL; tpOk.out === 1;
}

component main {public [xSign, xMag, nHat, pHat]} = NormalCdf();
