pragma circom 2.1.6;

// GENERATED by zk/scripts/gen-ncdf-circom.mjs — do not hand-edit. Regenerate and re-gate.
//
// THE STANDARD NORMAL CDF, COMPUTED IN A CIRCUIT.
//
// The roadmap said options-risk "requires exp and erf in-circuit, which is where this stops being
// arithmetic and starts being a research project", and greeksfp/greekssigned/parity were built to
// route around it by proving CONSISTENCY identities that cancel the transcendental instead of
// evaluating it. probe-cdf-residue.mjs measured the cost of that route: a service using
// Abramowitz-Stegun 7.1.26 instead of Hart satisfies ALL EIGHT identities to 3.3e-14 and prices a
// leg 19.4% wrong. So the identities are blind to the thing that matters, and put-call parity is
// blind too — the put is P = df*(K*N(-d2) - F*N(-d1)), so any N with N(-x) = 1 - N(x) makes
// C - P = df*(F - K) hold ALGEBRAICALLY with N cancelling.
//
// The premise was wrong, in the same way the Tier-3 premise was wrong. "erf" is not what the
// engine computes. The engine computes HART (1968):
//
//     N(-z) = e^{-z^2/2} * b(z) / d(z)        for 0 <= z < 7.0711
//
// A ratio is a multiplication: c*d = e*b. A polynomial is Horner. That leaves one transcendental,
// e^{-w} — and e^{-w} FACTORS over the binary expansion of w in a way erf does not:
//
//     w = sum_i b_i 2^i    =>    e^{-w} = prod_i (e^{-2^i})^{b_i}
//
// Every factor is a constant and every choice is a multiplexer, so exp is a product of selected
// constants — which is what a circuit does natively. The wall was never the transcendental. It was
// the fixed-point representation, exactly as it was for Tier 3.
//
// ── WHAT IS PROVEN ──
//   for the public point x, the public value n is the normal CDF at x, and the public value p is
//   its density, both evaluated by the recurrences below. The evaluator is pinned, not asserted:
//   every multiply carries a range-checked remainder, so the prover cannot choose a rounding.
//
// ── WHAT IS NOT ──
//   this pins n GIVEN x. It does not pin x. For options-risk, x is d1 or d2, and pinning those
//   needs ln(F/K) — which is the same exp gadget run backwards (L is the log of F/K iff
//   K*exp(L) = F), so it is another instance of this block and not a new problem. NOT BUILT HERE.
//   What IS measured in gateB7-5: n and p together over-determine x, so a caller who binds p to a
//   published gamma and n to a published delta pins x without any logarithm at all.
//
// ── THE TAIL ──
//   Hart switches to a continued fraction at z = 7.0711. This circuit does NOT carry that branch.
//   Above the split it proves a BOUND instead: the upper tail is under 2 / 2^32, and the
//   density under 2 / 2^32. That is a real weakening and it is published as `computed`, so a
//   reader can see which of the two statements they were given. Measured over a listed-book shape,
//   1.03% of legs land there; over a one-hour-to-one-week wing, 46.79% do.
//
// ── SCALE ── every quantity is an integer at 2^-32. The truncating multiply
//   out * 2^S + rem = a * b,  0 <= rem < 2^S
//   is one constraint plus an S-bit range check, and it is the dominant cost: 26 of them.

include "../../node_modules/circomlib/circuits/bitify.circom";
include "../../node_modules/circomlib/circuits/comparators.circom";
include "../../node_modules/circomlib/circuits/mux4.circom";

// a * b >> S, with the discarded remainder range-checked so the prover cannot pick a rounding.
// Without the range check `out` is unconstrained below the S-th bit and the whole evaluator is
// decoration — the same failure the mantissa lower bound in greeksfp existed to prevent.
template MulShift(S) {
    signal input a;
    signal input b;
    signal output out;
    signal rem;
    signal prod;
    prod <== a * b;
    out <-- prod \ (1 << S);
    rem <-- prod % (1 << S);
    prod === out * (1 << S) + rem;
    component rb = Num2Bits(S);
    rb.in <== rem;
}

template NormalCdf() {
    var S      = 32;
    var ONE    = 4294967296;                 // 1.0
    var NB_X   = 44;
    var NB_R   = 85;                       // derived: max(cHat*dHat, eHat*bHat) + 2, not rounded up
    var NB_P   = 68;
    var TOLC   = 12;                        // ulp; derived, see the block at the c relation
    var TOLP   = 10;
    var ZSPLIT = 30370005000;      // 7.07106781186547, where Hart changes branch
    var SQRT2PI = 10765886462;     // computed by Machin + integer sqrt, not quoted from a table
    var CDF_TAIL = 2;                   // N(-7.0711), the tail bound
    var PHI_TAIL = 2;                  // phi(7.0711), the density bound

    // ---- public interface -----------------------------------------------------------------
    signal input xSign;      // 0 when x >= 0, 1 when x < 0
    signal input xMag;       // |x| * 2^S
    signal input nHat;       // the claimed N(x) * 2^S
    signal input pHat;       // the claimed density phi(x) * 2^S

    signal output computed;  // 1 when the CDF was evaluated, 0 when only the tail bound was proven
    signal output tailC;     // the bound in force above the split, published so it is not implied
    signal output tailP;
    tailC <== CDF_TAIL;
    tailP <== PHI_TAIL;

    xSign * (xSign - 1) === 0;
    component rx = Num2Bits(NB_X);   rx.in <== xMag;
    component rn = Num2Bits(S + 1);  rn.in <== nHat;      // N is in [0,1], so S+1 bits is exact
    component rp = Num2Bits(S);      rp.in <== pHat;      // phi <= 0.3990 < 1
    component nLe = LessEqThan(S + 2); nLe.in[0] <== nHat; nLe.in[1] <== ONE; nLe.out === 1;

    // ---- which branch -------------------------------------------------------------------
    component split = LessThan(NB_X + 1);
    split.in[0] <== xMag;
    split.in[1] <== ZSPLIT;
    computed <== split.out;

    // The evaluator ALWAYS runs, on a clamped argument, so its own range checks can never be the
    // thing that fails on a tail input. Only the binding of its output to nHat/pHat is conditional.
    // Running it on the raw xMag instead would make W overflow at |x| = 386, which a real book
    // reaches, and the circuit would refuse where it means to bound.
    signal zc;
    zc <== xMag + (1 - computed) * (ZSPLIT - 1 - xMag);

    // ---- W = z^2 / 2, at 2^-S ------------------------------------------------------------
    signal sq;
    sq <== zc * zc;
    signal W;
    signal wRem;
    W    <-- sq \ (1 << 33);
    wRem <-- sq % (1 << 33);
    sq === W * (1 << 33) + wRem;
    component wrb = Num2Bits(33);  wrb.in <== wRem;
    component wbits = Num2Bits(37);  wbits.in <== W;

    // ---- e^{-W}: 10 groups of 4 bits, one Mux4 and one MulShift each -------------------------
    // 160 constants, generated at 200 fractional bits and re-derived by the gate.
    component mx[10];
    component em[10];
    signal acc[11];
    acc[0] <== ONE;
    mx[0] = Mux4();
    mx[0].c[0] <== 4294967296;
    mx[0].c[1] <== 4294967295;
    mx[0].c[2] <== 4294967294;
    mx[0].c[3] <== 4294967293;
    mx[0].c[4] <== 4294967292;
    mx[0].c[5] <== 4294967291;
    mx[0].c[6] <== 4294967290;
    mx[0].c[7] <== 4294967289;
    mx[0].c[8] <== 4294967288;
    mx[0].c[9] <== 4294967287;
    mx[0].c[10] <== 4294967286;
    mx[0].c[11] <== 4294967285;
    mx[0].c[12] <== 4294967284;
    mx[0].c[13] <== 4294967283;
    mx[0].c[14] <== 4294967282;
    mx[0].c[15] <== 4294967281;
    mx[0].s[0] <== wbits.out[0];
    mx[0].s[1] <== wbits.out[1];
    mx[0].s[2] <== wbits.out[2];
    mx[0].s[3] <== wbits.out[3];
    em[0] = MulShift(S);   em[0].a <== acc[0];   em[0].b <== mx[0].out;   acc[1] <== em[0].out;
    mx[1] = Mux4();
    mx[1].c[0] <== 4294967296;
    mx[1].c[1] <== 4294967280;
    mx[1].c[2] <== 4294967264;
    mx[1].c[3] <== 4294967248;
    mx[1].c[4] <== 4294967232;
    mx[1].c[5] <== 4294967216;
    mx[1].c[6] <== 4294967200;
    mx[1].c[7] <== 4294967184;
    mx[1].c[8] <== 4294967168;
    mx[1].c[9] <== 4294967152;
    mx[1].c[10] <== 4294967136;
    mx[1].c[11] <== 4294967120;
    mx[1].c[12] <== 4294967104;
    mx[1].c[13] <== 4294967088;
    mx[1].c[14] <== 4294967072;
    mx[1].c[15] <== 4294967056;
    mx[1].s[0] <== wbits.out[4];
    mx[1].s[1] <== wbits.out[5];
    mx[1].s[2] <== wbits.out[6];
    mx[1].s[3] <== wbits.out[7];
    em[1] = MulShift(S);   em[1].a <== acc[1];   em[1].b <== mx[1].out;   acc[2] <== em[1].out;
    mx[2] = Mux4();
    mx[2].c[0] <== 4294967296;
    mx[2].c[1] <== 4294967040;
    mx[2].c[2] <== 4294966784;
    mx[2].c[3] <== 4294966528;
    mx[2].c[4] <== 4294966272;
    mx[2].c[5] <== 4294966016;
    mx[2].c[6] <== 4294965760;
    mx[2].c[7] <== 4294965504;
    mx[2].c[8] <== 4294965248;
    mx[2].c[9] <== 4294964992;
    mx[2].c[10] <== 4294964736;
    mx[2].c[11] <== 4294964480;
    mx[2].c[12] <== 4294964224;
    mx[2].c[13] <== 4294963968;
    mx[2].c[14] <== 4294963712;
    mx[2].c[15] <== 4294963456;
    mx[2].s[0] <== wbits.out[8];
    mx[2].s[1] <== wbits.out[9];
    mx[2].s[2] <== wbits.out[10];
    mx[2].s[3] <== wbits.out[11];
    em[2] = MulShift(S);   em[2].a <== acc[2];   em[2].b <== mx[2].out;   acc[3] <== em[2].out;
    mx[3] = Mux4();
    mx[3].c[0] <== 4294967296;
    mx[3].c[1] <== 4294963200;
    mx[3].c[2] <== 4294959104;
    mx[3].c[3] <== 4294955008;
    mx[3].c[4] <== 4294950912;
    mx[3].c[5] <== 4294946816;
    mx[3].c[6] <== 4294942720;
    mx[3].c[7] <== 4294938624;
    mx[3].c[8] <== 4294934528;
    mx[3].c[9] <== 4294930432;
    mx[3].c[10] <== 4294926336;
    mx[3].c[11] <== 4294922240;
    mx[3].c[12] <== 4294918144;
    mx[3].c[13] <== 4294914048;
    mx[3].c[14] <== 4294909952;
    mx[3].c[15] <== 4294905856;
    mx[3].s[0] <== wbits.out[12];
    mx[3].s[1] <== wbits.out[13];
    mx[3].s[2] <== wbits.out[14];
    mx[3].s[3] <== wbits.out[15];
    em[3] = MulShift(S);   em[3].a <== acc[3];   em[3].b <== mx[3].out;   acc[4] <== em[3].out;
    mx[4] = Mux4();
    mx[4].c[0] <== 4294967296;
    mx[4].c[1] <== 4294901760;
    mx[4].c[2] <== 4294836226;
    mx[4].c[3] <== 4294770692;
    mx[4].c[4] <== 4294705160;
    mx[4].c[5] <== 4294639628;
    mx[4].c[6] <== 4294574098;
    mx[4].c[7] <== 4294508568;
    mx[4].c[8] <== 4294443040;
    mx[4].c[9] <== 4294377512;
    mx[4].c[10] <== 4294311986;
    mx[4].c[11] <== 4294246460;
    mx[4].c[12] <== 4294180936;
    mx[4].c[13] <== 4294115412;
    mx[4].c[14] <== 4294049890;
    mx[4].c[15] <== 4293984368;
    mx[4].s[0] <== wbits.out[16];
    mx[4].s[1] <== wbits.out[17];
    mx[4].s[2] <== wbits.out[18];
    mx[4].s[3] <== wbits.out[19];
    em[4] = MulShift(S);   em[4].a <== acc[4];   em[4].b <== mx[4].out;   acc[5] <== em[4].out;
    mx[5] = Mux4();
    mx[5].c[0] <== 4294967296;
    mx[5].c[1] <== 4293918848;
    mx[5].c[2] <== 4292870656;
    mx[5].c[3] <== 4291822720;
    mx[5].c[4] <== 4290775039;
    mx[5].c[5] <== 4289727615;
    mx[5].c[6] <== 4288680446;
    mx[5].c[7] <== 4287633532;
    mx[5].c[8] <== 4286586875;
    mx[5].c[9] <== 4285540472;
    mx[5].c[10] <== 4284494326;
    mx[5].c[11] <== 4283448434;
    mx[5].c[12] <== 4282402798;
    mx[5].c[13] <== 4281357417;
    mx[5].c[14] <== 4280312291;
    mx[5].c[15] <== 4279267421;
    mx[5].s[0] <== wbits.out[20];
    mx[5].s[1] <== wbits.out[21];
    mx[5].s[2] <== wbits.out[22];
    mx[5].s[3] <== wbits.out[23];
    em[5] = MulShift(S);   em[5].a <== acc[5];   em[5].b <== mx[5].out;   acc[6] <== em[5].out;
    mx[6] = Mux4();
    mx[6].c[0] <== 4294967296;
    mx[6].c[1] <== 4278222805;
    mx[6].c[2] <== 4261543595;
    mx[6].c[3] <== 4244929411;
    mx[6].c[4] <== 4228380000;
    mx[6].c[5] <== 4211895109;
    mx[6].c[6] <== 4195474486;
    mx[6].c[7] <== 4179117881;
    mx[6].c[8] <== 4162825044;
    mx[6].c[9] <== 4146595727;
    mx[6].c[10] <== 4130429683;
    mx[6].c[11] <== 4114326664;
    mx[6].c[12] <== 4098286424;
    mx[6].c[13] <== 4082308719;
    mx[6].c[14] <== 4066393306;
    mx[6].c[15] <== 4050539941;
    mx[6].s[0] <== wbits.out[24];
    mx[6].s[1] <== wbits.out[25];
    mx[6].s[2] <== wbits.out[26];
    mx[6].s[3] <== wbits.out[27];
    em[6] = MulShift(S);   em[6].a <== acc[6];   em[6].b <== mx[6].out;   acc[7] <== em[6].out;
    mx[7] = Mux4();
    mx[7].c[0] <== 4294967296;
    mx[7].c[1] <== 4034748382;
    mx[7].c[2] <== 3790295335;
    mx[7].c[3] <== 3560652950;
    mx[7].c[4] <== 3344923893;
    mx[7].c[5] <== 3142265200;
    mx[7].c[6] <== 2951884975;
    mx[7].c[7] <== 2773039306;
    mx[7].c[8] <== 2605029347;
    mx[7].c[9] <== 2447198598;
    mx[7].c[10] <== 2298930330;
    mx[7].c[11] <== 2159645183;
    mx[7].c[12] <== 2028798896;
    mx[7].c[13] <== 1905880184;
    mx[7].c[14] <== 1790408741;
    mx[7].c[15] <== 1681933360;
    mx[7].s[0] <== wbits.out[28];
    mx[7].s[1] <== wbits.out[29];
    mx[7].s[2] <== wbits.out[30];
    mx[7].s[3] <== wbits.out[31];
    em[7] = MulShift(S);   em[7].a <== acc[7];   em[7].b <== mx[7].out;   acc[8] <== em[7].out;
    mx[8] = Mux4();
    mx[8].c[0] <== 4294967296;
    mx[8].c[1] <== 1580030169;
    mx[8].c[2] <== 581260615;
    mx[8].c[3] <== 213833830;
    mx[8].c[4] <== 78665070;
    mx[8].c[5] <== 28939262;
    mx[8].c[6] <== 10646160;
    mx[8].c[7] <== 3916503;
    mx[8].c[8] <== 1440801;
    mx[8].c[9] <== 530041;
    mx[8].c[10] <== 194991;
    mx[8].c[11] <== 71733;
    mx[8].c[12] <== 26389;
    mx[8].c[13] <== 9708;
    mx[8].c[14] <== 3571;
    mx[8].c[15] <== 1314;
    mx[8].s[0] <== wbits.out[32];
    mx[8].s[1] <== wbits.out[33];
    mx[8].s[2] <== wbits.out[34];
    mx[8].s[3] <== wbits.out[35];
    em[8] = MulShift(S);   em[8].a <== acc[8];   em[8].b <== mx[8].out;   acc[9] <== em[8].out;
    mx[9] = Mux4();
    mx[9].c[0] <== 4294967296;
    mx[9].c[1] <== 483;
    mx[9].c[2] <== 0;
    mx[9].c[3] <== 0;
    mx[9].c[4] <== 0;
    mx[9].c[5] <== 0;
    mx[9].c[6] <== 0;
    mx[9].c[7] <== 0;
    mx[9].c[8] <== 0;
    mx[9].c[9] <== 0;
    mx[9].c[10] <== 0;
    mx[9].c[11] <== 0;
    mx[9].c[12] <== 0;
    mx[9].c[13] <== 0;
    mx[9].c[14] <== 0;
    mx[9].c[15] <== 0;
    mx[9].s[0] <== wbits.out[36];
    mx[9].s[1] <== 0;
    mx[9].s[2] <== 0;
    mx[9].s[3] <== 0;
    em[9] = MulShift(S);   em[9].a <== acc[9];   em[9].b <== mx[9].out;   acc[10] <== em[9].out;
    signal eHat;
    eHat <== acc[10];

    // ---- Hart's two polynomials, Horner ----------------------------------------------------
    component bm[6];
    signal bh[7];
    bh[0] <== 151451270;
    bm[0] = MulShift(S);   bm[0].a <== bh[0];   bm[0].b <== zc;   bh[1] <== bm[0].out + 3008122356;
    bm[1] = MulShift(S);   bm[1].a <== bh[1];   bm[1].b <== zc;   bh[2] <== bm[1].out + 27375959210;
    bm[2] = MulShift(S);   bm[2].a <== bh[2];   bm[2].b <== zc;   bh[3] <== bm[2].out + 145654650720;
    bm[3] = MulShift(S);   bm[3].a <== bh[3];   bm[3].b <== zc;   bh[4] <== bm[3].out + 481376891542;
    bm[4] = MulShift(S);   bm[4].a <== bh[4];   bm[4].b <== zc;   bh[5] <== bm[4].out + 950105160980;
    bm[5] = MulShift(S);   bm[5].a <== bh[5];   bm[5].b <== zc;   bh[6] <== bm[5].out + 945781296038;
    component dm[7];
    signal dh[8];
    dh[0] <== 379625062;
    dm[0] = MulShift(S);   dm[0].a <== dh[0];   dm[0].b <== zc;   dh[1] <== dm[0].out + 7540533049;
    dm[1] = MulShift(S);   dm[1].a <== dh[1];   dm[1].b <== zc;   dh[2] <== dm[1].out + 68995117340;
    dm[2] = MulShift(S);   dm[2].a <== dh[2];   dm[2].b <== zc;   dh[3] <== dm[2].out + 372720406735;
    dm[3] = MulShift(S);   dm[3].a <== dh[3];   dm[3].b <== zc;   dh[4] <== dm[3].out + 1273733749672;
    dm[4] = MulShift(S);   dm[4].a <== dh[4];   dm[4].b <== zc;   dh[5] <== dm[4].out + 2737327112003;
    dm[5] = MulShift(S);   dm[5].a <== dh[5];   dm[5].b <== zc;   dh[6] <== dm[5].out + 3409458909971;
    dm[6] = MulShift(S);   dm[6].a <== dh[6];   dm[6].b <== zc;   dh[7] <== dm[6].out + 1891562592076;
    signal bHat;  signal dHat;
    bHat <== bh[6];
    dHat <== dh[7];

    // ---- c, the upper tail, and its relation to n -----------------------------------------
    // Hart returns the UPPER tail c and the CDF is c for x <= 0 and 1 - c for x > 0. Written as
    // one quadratic rather than a branch, since a circuit has no branches.
    signal cHat;
    cHat <== ONE - nHat + xSign * (2 * nHat - ONE);
    // c is an upper tail at |x| >= 0, so it never exceeds a half. Cheap, and it stops a prover
    // handing in the complement and letting the sign bit absorb it.
    component cLe = LessEqThan(S + 2);  cLe.in[0] <== cHat;  cLe.in[1] <== ONE \ 2;  cLe.out === 1;

    // c*d = e*b, which is the division without dividing. An absolute error of T ulp in c shows up
    // here as T*dHat, so the tolerance is TOLC*dHat and TOLC reads directly in ulp.
    // TOLC = 12, DERIVED in probe-ncdf-tol.mjs and not chosen: 19 ulp of accumulated exp error
    // times b/d <= 0.5, plus 3.4e-3 from b, 1.7e-3 from d, plus 1.0023 for this relation's own
    // floor remainder = 10.507 ulp worst, at z = 0. The real engine's worst leg uses 18.3% of it,
    // and gateB7-5 shows a value 13 ulp out IS refused — otherwise it is not a bound.
    signal lhs;   lhs <== cHat * dHat;
    signal eb;    eb  <== eHat * bHat;
    signal resid; resid <== computed * (lhs - eb);
    signal tolC;  tolC <== TOLC * dHat;
    signal cShift; cShift <== 2 * resid + tolC;
    // NO separate Num2Bits on cShift. LessEqThan(n) already decomposes in[0] + 2^n - in[1] into
    // n+1 bits, so a cShift that is out of range — including a field-wrapped negative one — makes
    // that decomposition unsatisfiable and the prover cannot produce a witness at all. The extra
    // check the sibling circuits carry can only turn an accept into a refusal, never the reverse,
    // and it costs NB_R constraints. gateB7-5 confirms the refusal by hand rather than trusting
    // this paragraph.
    component cOk = LessEqThan(NB_R); cOk.in[0] <== cShift; cOk.in[1] <== 2 * tolC; cOk.out === 1;

    // ---- the density, which the CDF has already computed ----------------------------------
    // phi(x) = e^{-x^2/2}/sqrt(2*pi), and e^{-x^2/2} is `eHat`, the exp intermediate above. So the
    // density costs one multiply. This matters more than it looks: df*phi(d1) is the factor that
    // CANCELS between any two greeks, which is what let the consistency identities exist without a
    // transcendental. Pinning it is what stops it cancelling.
    signal pd;    pd <== pHat * SQRT2PI;
    signal pe;    pe <== eHat * ONE;
    signal presid; presid <== computed * (pd - pe);
    signal tolP;  tolP <== TOLP * SQRT2PI;
    signal pShift; pShift <== 2 * presid + tolP;
    component pOk = LessEqThan(NB_P); pOk.in[0] <== pShift; pOk.in[1] <== 2 * tolP; pOk.out === 1;

    // ---- above the split, the bound ------------------------------------------------------
    // Both functions are decreasing on the tail, so their value AT the split is the maximum over
    // it. gateB7-5 measures the true maximum and refuses if either constant is under it.
    signal tailc;  tailc <== (1 - computed) * cHat;
    component tcOk = LessEqThan(S + 2); tcOk.in[0] <== tailc; tcOk.in[1] <== CDF_TAIL; tcOk.out === 1;
    signal tailp;  tailp <== (1 - computed) * pHat;
    component tpOk = LessEqThan(S + 2); tpOk.in[0] <== tailp; tpOk.in[1] <== PHI_TAIL; tpOk.out === 1;
}

component main {public [xSign, xMag, nHat, pHat]} = NormalCdf();
